language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r spring-boot-practice *
  - mkdir -p deploy
  - mv spring-boot-practice.zip deploy/spring-boot-practice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting value
    secret_access_key: $AWS_SECRET_KEY
    bucket: yoonoh-springboot-build # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 로
    local_dir: deploy # before_deploy 에서 생성한 directory
    wait-until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting value
    secret_access_key: $AWS_SECRET_KEY
    bucket: yoonoh-springboot-build
    key: spring-boot-practice.zip # 빌드파일을 압축해서 전달
    bundle_type: zip
    application: yoonoh-spring-practice # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: yoonoh-spring-practice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

# CI 실행 완료시 이메일 알람
notifications:
  email:
    recipients:
      - xkakak142@naver.com